# Use postgres/example user/password credentials
version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always

    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: exampreparation
      PGDATA: C:/Users/Dmitry/PycharmProjects/preparationexam/exampreparation
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"